### PR TITLE
Bring up to speed with angerman

### PR DESCRIPTION
**Pull request by schell**
@angerman - what's the status of your branch? I'd like to get this repo up and running again.

### CODE REVIEW

**Comment by angerman** [comment]
This should be good to go. Do you want a PR?

I've a few more ideas for improvements beyond, what this repo does so far. However, I'm focused on improving the ghc llvm backend for now.

**Comment by schell** [comment]
Thank you! Do you think this project could be helped by using nix? We are nixing at work and I may be able to get some significant help in that area.

**Comment by angerman** [comment]
Eventually nix, might be a good option. However imo (and I do actually like nix a lot), it would raise the bar quite a bit for newcomers.

What I'd like to see is some kind of `boot.sh` script, that generates the `<arch>-...-<os>` scripts. As those are almost identical copies of each other, with only the arch and os modified. It's way too
easy to forget to edit one of the scripts and end up with strange errors.

Providing a few nix expressions as an alternative option would be a nice addition though. As stated though, I'm not a big fan of completely nixifying this, as there would be no option for nix-less users.

**Comment by angerman** [comment]
As I've just found out, we might want to drop i386, e.g. the 32bit simulator. On the one hand apple will soon drop 32bit support anyway, and it seems like recent llvm version (e.g. 4.0) fail to even produce proper code for i386 for parts of ghc.

**Comment by schell** [comment]
I'm okay with this. My main concern is making sure this works with the most recent version of Xcode/iOS. 

Do you know how/where the cross compiler binaries get generated and if newer ones are already available?

**Comment by schell** [comment]
@angerman also - it seems like some of your changes remove the need to download llvm, since we're using the xcode installed version, is this true?

**Comment by angerman** [comment]
building a ghc cross compiler has been a lucky endeavor at best. I'm currently working quite a bit on getting the state of ghc for ios into much better shape. The llvm version ghc targets is (as of 8.2) lvlm 3.9, and 3.7 before that. To build ghc, with a recent ghc, you need llvm 3.7 to build the stage1 compiler, and llvm 3.9 to build anything with the resulting stage1 compiler.

Ideally we'd be able to provide ghc binaries for ios and android. However as it is right now, I don't believe that a) downloading the ios ghc binaries, nor b) downloading llvm automatically are good solutions. The repository should be explicit about the requirements, even though that implies being less magically automatic.

With 8.4 we might either ship a ghc-clang with ghc, or get lucky and be able to use the stock llvm5 or llvm6, at that point ios and android binary distributions should hopefully become feasible.

**Comment by schell** [comment]
Thanks for all your help, @angerman.

**Pull request merged**
